ALTER TABLE mcp_servers ADD COLUMN IF NOT EXISTS claim_token VARCHAR(255);
ALTER TABLE mcp_servers ADD COLUMN IF NOT EXISTS claimed_at TIMESTAMP;
ALTER TABLE mcp_servers ADD COLUMN IF NOT EXISTS owner_email VARCHAR(255);
