import { drizzle } from 'drizzle-orm/postgres-js';
import postgres from 'postgres';
import { mcpServers } from '../lib/db/schema';
import * as dotenv from 'dotenv';

dotenv.config({ path: '.env.local' });

const client = postgres(process.env.DATABASE_URL!);
const db = drizzle(client);

const servers = [
  {
    name: 'PostgreSQL MCP',
    slug: 'postgresql-mcp',
    tagline: 'Connect AI agents to PostgreSQL databases with full query access',
    description: 'Full-featured PostgreSQL connector for AI agents. Supports queries, schema inspection, migrations, and real-time data access. Works with Claude, GPT-4, and any MCP-compatible agent.',
    category: 'Database',
    protocol: 'MCP',
    githubUrl: 'https://github.com/modelcontextprotocol/servers',
    npmPackage: '@modelcontextprotocol/server-postgres',
    installCommand: 'npm install @modelcontextprotocol/server-postgres',
    authorName: 'Anthropic',
    authorEmail: 'mcp@anthropic.com',
    status: 'approved',
    isVerified: true,
    isFeatured: true,
    viewCount: 4200,
    installCount: 2300,
    ratingAvg: '4.9',
    ratingCount: 187,
  },
  {
    name: 'GitHub MCP Server',
    slug: 'github-mcp',
    tagline: 'Create issues, manage PRs, and interact with repositories from your AI agent',
    description: 'Comprehensive GitHub integration for AI agents. Create and manage issues, review pull requests, read repository contents, search code, and automate workflows directly from your AI pipeline.',
    category: 'Development',
    protocol: 'MCP',
    githubUrl: 'https://github.com/modelcontextprotocol/servers',
    npmPackage: '@modelcontextprotocol/server-github',
    installCommand: 'npm install @modelcontextprotocol/server-github',
    authorName: 'Anthropic',
    authorEmail: 'mcp@anthropic.com',
    status: 'approved',
    isVerified: true,
    isFeatured: true,
    viewCount: 5800,
    installCount: 3100,
    ratingAvg: '4.9',
    ratingCount: 243,
  },
  {
    name: 'Slack MCP Integration',
    slug: 'slack-mcp',
    tagline: 'Send messages, read channels, and manage Slack workspaces from AI agents',
    description: 'Full Slack workspace integration for AI agents. Send and read messages, manage channels, search message history, and automate notifications. Supports both direct messages and channel communication.',
    category: 'Communication',
    protocol: 'MCP',
    githubUrl: 'https://github.com/modelcontextprotocol/servers',
    npmPackage: '@modelcontextprotocol/server-slack',
    installCommand: 'npm install @modelcontextprotocol/server-slack',
    authorName: 'Anthropic',
    authorEmail: 'mcp@anthropic.com',
    status: 'approved',
    isVerified: true,
    isFeatured: false,
    viewCount: 3100,
    installCount: 1800,
    ratingAvg: '4.8',
    ratingCount: 156,
  },
  {
    name: 'Brave Search MCP',
    slug: 'brave-search-mcp',
    tagline: 'Give your AI agent real-time web search capabilities via Brave',
    description: 'Integrate real-time web search into your AI agent using the Brave Search API. Supports web search, news search, and image search. Privacy-focused alternative to Google.',
    category: 'AI & ML',
    protocol: 'MCP',
    githubUrl: 'https://github.com/modelcontextprotocol/servers',
    npmPackage: '@modelcontextprotocol/server-brave-search',
    installCommand: 'npm install @modelcontextprotocol/server-brave-search',
    authorName: 'Anthropic',
    authorEmail: 'mcp@anthropic.com',
    status: 'approved',
    isVerified: true,
    isFeatured: false,
    viewCount: 2900,
    installCount: 1600,
    ratingAvg: '4.7',
    ratingCount: 128,
  },
  {
    name: 'Filesystem MCP',
    slug: 'filesystem-mcp',
    tagline: 'Let AI agents read and write files on your local filesystem',
    description: 'Secure filesystem access for AI agents with configurable directory permissions. Read files, write outputs, list directories, and manage files. Essential for any agent that needs to work with local data.',
    category: 'Development',
    protocol: 'MCP',
    githubUrl: 'https://github.com/modelcontextprotocol/servers',
    npmPackage: '@modelcontextprotocol/server-filesystem',
    installCommand: 'npm install @modelcontextprotocol/server-filesystem',
    authorName: 'Anthropic',
    authorEmail: 'mcp@anthropic.com',
    status: 'approved',
    isVerified: true,
    isFeatured: false,
    viewCount: 6200,
    installCount: 4100,
    ratingAvg: '4.8',
    ratingCount: 312,
  },
  {
    name: 'Google Drive MCP',
    slug: 'google-drive-mcp',
    tagline: 'Read, write, and manage Google Drive files from your AI agent',
    description: 'Full Google Drive integration — read documents, sheets, and presentations. Create and update files, search across your Drive, and manage folder structures. Supports Docs, Sheets, Slides, and raw files.',
    category: 'Productivity',
    protocol: 'MCP',
    githubUrl: 'https://github.com/modelcontextprotocol/servers',
    npmPackage: '@modelcontextprotocol/server-gdrive',
    installCommand: 'npm install @modelcontextprotocol/server-gdrive',
    authorName: 'Anthropic',
    authorEmail: 'mcp@anthropic.com',
    status: 'approved',
    isVerified: true,
    isFeatured: false,
    viewCount: 2400,
    installCount: 1200,
    ratingAvg: '4.6',
    ratingCount: 98,
  },
  {
    name: 'SQLite MCP Server',
    slug: 'sqlite-mcp',
    tagline: 'Query and manage SQLite databases directly from AI agents',
    description: 'Lightweight SQLite integration for AI agents. Run queries, inspect schemas, insert and update records, and manage databases. Perfect for local development and lightweight applications.',
    category: 'Database',
    protocol: 'MCP',
    githubUrl: 'https://github.com/modelcontextprotocol/servers',
    npmPackage: '@modelcontextprotocol/server-sqlite',
    installCommand: 'npm install @modelcontextprotocol/server-sqlite',
    authorName: 'Anthropic',
    authorEmail: 'mcp@anthropic.com',
    status: 'approved',
    isVerified: true,
    isFeatured: false,
    viewCount: 3400,
    installCount: 2100,
    ratingAvg: '4.8',
    ratingCount: 167,
  },
  {
    name: 'Notion MCP',
    slug: 'notion-mcp',
    tagline: 'Read and write Notion pages, databases, and blocks from AI agents',
    description: 'Complete Notion workspace integration. Read pages and databases, create and update content, query databases with filters, and manage your knowledge base. Works with Claude and GPT agents.',
    category: 'Productivity',
    protocol: 'MCP',
    githubUrl: 'https://github.com/makenotion/notion-mcp-server',
    npmPackage: '@notionhq/notion-mcp-server',
    installCommand: 'npm install @notionhq/notion-mcp-server',
    authorName: 'Notion',
    authorEmail: 'developers@notion.so',
    status: 'approved',
    isVerified: true,
    isFeatured: false,
    viewCount: 2800,
    installCount: 1500,
    ratingAvg: '4.7',
    ratingCount: 134,
  },
  {
    name: 'AWS S3 MCP',
    slug: 'aws-s3-mcp',
    tagline: 'Upload, download, and manage S3 buckets from AI agents',
    description: 'Full AWS S3 integration for AI agents. List buckets and objects, upload and download files, manage permissions, and work with S3-compatible storage. Supports presigned URLs and multipart uploads.',
    category: 'Cloud',
    protocol: 'MCP',
    githubUrl: 'https://github.com/aws/mcp',
    npmPackage: '@aws/mcp-server-s3',
    installCommand: 'npm install @aws/mcp-server-s3',
    authorName: 'Amazon Web Services',
    authorEmail: 'mcp@amazon.com',
    status: 'approved',
    isVerified: true,
    isFeatured: false,
    viewCount: 1900,
    installCount: 980,
    ratingAvg: '4.6',
    ratingCount: 87,
  },
  {
    name: 'Stripe MCP Server',
    slug: 'stripe-mcp',
    tagline: 'Query customers, payments, and invoices from your AI agent',
    description: 'Stripe payment data integration for AI agents. Query customers, subscriptions, payments, and invoices. Create payment links, check revenue analytics, and manage refunds.',
    category: 'Finance',
    protocol: 'MCP',
    githubUrl: 'https://github.com/stripe/agent-toolkit',
    npmPackage: '@stripe/agent-toolkit',
    installCommand: 'npm install @stripe/agent-toolkit',
    authorName: 'Stripe',
    authorEmail: 'dev-platform@stripe.com',
    status: 'approved',
    isVerified: true,
    isFeatured: false,
    viewCount: 2200,
    installCount: 1100,
    ratingAvg: '4.7',
    ratingCount: 102,
  },
  {
    name: 'Supabase MCP',
    slug: 'supabase-mcp',
    tagline: 'Query Supabase tables and call Edge Functions from your AI agent',
    description: 'Complete Supabase integration for AI agents. Run database queries, call Edge Functions, manage auth users, work with storage buckets, and access realtime data.',
    category: 'Database',
    protocol: 'MCP',
    githubUrl: 'https://github.com/supabase/mcp-server-supabase',
    npmPackage: '@supabase/mcp-server-supabase',
    installCommand: 'npm install @supabase/mcp-server-supabase',
    authorName: 'Supabase',
    authorEmail: 'mcp@supabase.io',
    status: 'approved',
    isVerified: true,
    isFeatured: false,
    viewCount: 3100,
    installCount: 1700,
    ratingAvg: '4.8',
    ratingCount: 143,
  },
  {
    name: 'Puppeteer MCP',
    slug: 'puppeteer-mcp',
    tagline: 'Let AI agents control a browser — click, scrape, screenshot, and automate',
    description: 'Full browser automation for AI agents using Puppeteer. Navigate pages, click elements, fill forms, take screenshots, scrape data, and automate web workflows.',
    category: 'Development',
    protocol: 'MCP',
    githubUrl: 'https://github.com/modelcontextprotocol/servers',
    npmPackage: '@modelcontextprotocol/server-puppeteer',
    installCommand: 'npm install @modelcontextprotocol/server-puppeteer',
    authorName: 'Anthropic',
    authorEmail: 'mcp@anthropic.com',
    status: 'approved',
    isVerified: true,
    isFeatured: false,
    viewCount: 4700,
    installCount: 2900,
    ratingAvg: '4.8',
    ratingCount: 218,
  },
  {
    name: 'Linear MCP',
    slug: 'linear-mcp',
    tagline: 'Create issues, update projects, and manage Linear workflows from AI agents',
    description: 'Linear project management integration. Create and update issues, manage projects and cycles, assign work, track progress, and query your team backlog.',
    category: 'Development',
    protocol: 'MCP',
    githubUrl: 'https://github.com/linear/linear-mcp',
    npmPackage: '@linear/mcp-server',
    installCommand: 'npm install @linear/mcp-server',
    authorName: 'Linear',
    authorEmail: 'mcp@linear.app',
    status: 'approved',
    isVerified: false,
    isFeatured: false,
    viewCount: 1400,
    installCount: 720,
    ratingAvg: '4.5',
    ratingCount: 64,
  },
  {
    name: 'Redis MCP Server',
    slug: 'redis-mcp',
    tagline: 'Read and write Redis keys, lists, and hashes from AI agents',
    description: 'Redis data store integration for AI agents. Get/set keys, work with lists, hashes, sets, and sorted sets. Use Redis as agent memory, session store, or cache.',
    category: 'Database',
    protocol: 'MCP',
    githubUrl: 'https://github.com/modelcontextprotocol/servers',
    npmPackage: '@modelcontextprotocol/server-redis',
    installCommand: 'npm install @modelcontextprotocol/server-redis',
    authorName: 'Anthropic',
    authorEmail: 'mcp@anthropic.com',
    status: 'approved',
    isVerified: false,
    isFeatured: false,
    viewCount: 1800,
    installCount: 950,
    ratingAvg: '4.6',
    ratingCount: 79,
  },
  {
    name: 'Jira GPT Action',
    slug: 'jira-gpt-action',
    tagline: 'Create and manage Jira tickets directly from ChatGPT',
    description: 'GPT Action integration for Atlassian Jira. Create, update, and search issues, manage sprints, track project progress, and automate ticket workflows using natural language in ChatGPT.',
    category: 'Productivity',
    protocol: 'OpenAI',
    githubUrl: 'https://github.com/atlassian/jira-gpt-actions',
    npmPackage: null,
    installCommand: 'Import schema URL into ChatGPT Actions',
    authorName: 'Atlassian',
    authorEmail: 'developers@atlassian.com',
    status: 'approved',
    isVerified: true,
    isFeatured: false,
    viewCount: 1600,
    installCount: 840,
    ratingAvg: '4.5',
    ratingCount: 73,
  },
];

async function seed() {
  console.log('🌱 Seeding ForgeLink database...');
  try {
    await db.delete(mcpServers);
    console.log('🗑️  Cleared existing servers');
    const inserted = await db.insert(mcpServers).values(servers as any).returning();
    console.log(`✅ Inserted ${inserted.length} servers`);
    console.log(`  Approved: ${inserted.filter(s => s.status === 'approved').length}`);
    console.log(`  Verified: ${inserted.filter(s => s.isVerified).length}`);
    console.log(`  Featured: ${inserted.filter(s => s.isFeatured).length}`);
  } catch (error) {
    console.error('❌ Seed failed:', error);
    throw error;
  } finally {
    await client.end();
  }
}

seed();
