import { drizzle } from 'drizzle-orm/postgres-js';
import postgres from 'postgres';
import { mcpServers } from '../lib/db/schema';
import * as dotenv from 'dotenv';

dotenv.config({ path: '.env.local' });

const client = postgres(process.env.DATABASE_URL!);
const db = drizzle(client);

const newServers = [
  // DATABASE
  {
    name: 'MongoDB MCP',
    slug: 'mongodb-mcp',
    tagline: 'Query and manage MongoDB collections from AI agents',
    description: 'Full MongoDB integration for AI agents. Run aggregation pipelines, insert and update documents, manage indexes, and inspect schemas. Works with Atlas and self-hosted instances.',
    category: 'Database', protocol: 'MCP',
    githubUrl: 'https://github.com/mongodb/mongodb-mcp-server',
    npmPackage: '@mongodb/mcp-server',
    installCommand: 'npm install @mongodb/mcp-server',
    authorName: 'MongoDB', authorEmail: 'devrel@mongodb.com',
    status: 'approved', isVerified: true, isFeatured: false,
    viewCount: 3200, installCount: 1800, ratingAvg: '4.7', ratingCount: 154,
  },
  {
    name: 'PlanetScale MCP',
    slug: 'planetscale-mcp',
    tagline: 'Serverless MySQL for AI agents via PlanetScale',
    description: 'Connect AI agents to PlanetScale serverless MySQL. Run queries, inspect branches, manage schema changes, and work with deploy requests — all from your agent.',
    category: 'Database', protocol: 'MCP',
    githubUrl: 'https://github.com/planetscale/mcp-server',
    npmPackage: '@planetscale/mcp-server',
    installCommand: 'npm install @planetscale/mcp-server',
    authorName: 'PlanetScale', authorEmail: 'mcp@planetscale.com',
    status: 'approved', isVerified: true, isFeatured: false,
    viewCount: 1700, installCount: 890, ratingAvg: '4.6', ratingCount: 78,
  },
  {
    name: 'Neon MCP',
    slug: 'neon-mcp',
    tagline: 'Serverless Postgres branching and queries for AI agents',
    description: 'Neon serverless Postgres integration. Create database branches, run queries, manage connection pools, and scale to zero automatically. Ideal for AI dev workflows.',
    category: 'Database', protocol: 'MCP',
    githubUrl: 'https://github.com/neondatabase/mcp-server-neon',
    npmPackage: '@neondatabase/mcp-server-neon',
    installCommand: 'npm install @neondatabase/mcp-server-neon',
    authorName: 'Neon', authorEmail: 'devrel@neon.tech',
    status: 'approved', isVerified: true, isFeatured: false,
    viewCount: 2100, installCount: 1100, ratingAvg: '4.8', ratingCount: 96,
  },
  {
    name: 'Turso MCP',
    slug: 'turso-mcp',
    tagline: 'Edge SQLite at scale — query Turso databases from AI agents',
    description: 'Turso libSQL integration for AI agents. Query edge databases, manage replicas, run migrations, and work with embedded SQLite. Great for latency-sensitive agent workloads.',
    category: 'Database', protocol: 'MCP',
    githubUrl: 'https://github.com/tursodatabase/turso-mcp',
    npmPackage: '@turso/mcp-server',
    installCommand: 'npm install @turso/mcp-server',
    authorName: 'Turso', authorEmail: 'dev@turso.tech',
    status: 'approved', isVerified: false, isFeatured: false,
    viewCount: 980, installCount: 490, ratingAvg: '4.5', ratingCount: 43,
  },
  // DEVELOPMENT
  {
    name: 'GitLab MCP',
    slug: 'gitlab-mcp',
    tagline: 'Manage GitLab repos, MRs, and pipelines from AI agents',
    description: 'Full GitLab integration for AI agents. Create and merge merge requests, trigger CI/CD pipelines, manage issues and milestones, and read repository contents.',
    category: 'Development', protocol: 'MCP',
    githubUrl: 'https://github.com/modelcontextprotocol/servers',
    npmPackage: '@modelcontextprotocol/server-gitlab',
    installCommand: 'npm install @modelcontextprotocol/server-gitlab',
    authorName: 'Anthropic', authorEmail: 'mcp@anthropic.com',
    status: 'approved', isVerified: true, isFeatured: false,
    viewCount: 2600, installCount: 1400, ratingAvg: '4.7', ratingCount: 121,
  },
  {
    name: 'Docker MCP',
    slug: 'docker-mcp',
    tagline: 'Manage containers, images, and networks from AI agents',
    description: 'Docker integration for AI agents. List and manage containers, pull and build images, inspect logs, manage networks and volumes, and run commands inside containers.',
    category: 'Development', protocol: 'MCP',
    githubUrl: 'https://github.com/docker/mcp-servers',
    npmPackage: '@docker/mcp-server',
    installCommand: 'npm install @docker/mcp-server',
    authorName: 'Docker', authorEmail: 'mcp@docker.com',
    status: 'approved', isVerified: true, isFeatured: false,
    viewCount: 3400, installCount: 1900, ratingAvg: '4.8', ratingCount: 167,
  },
  {
    name: 'Vercel MCP',
    slug: 'vercel-mcp',
    tagline: 'Deploy projects, manage domains, and read logs from AI agents',
    description: 'Vercel platform integration for AI agents. Trigger deployments, manage environment variables, inspect build logs, manage domains, and monitor edge function performance.',
    category: 'Development', protocol: 'MCP',
    githubUrl: 'https://github.com/vercel/mcp-adapter',
    npmPackage: '@vercel/mcp-adapter',
    installCommand: 'npm install @vercel/mcp-adapter',
    authorName: 'Vercel', authorEmail: 'devrel@vercel.com',
    status: 'approved', isVerified: true, isFeatured: false,
    viewCount: 2900, installCount: 1600, ratingAvg: '4.8', ratingCount: 142,
  },
  {
    name: 'VS Code MCP',
    slug: 'vscode-mcp',
    tagline: 'Read files, run terminals, and control VS Code from AI agents',
    description: 'VS Code integration that lets AI agents interact with your editor. Read and write files, run terminal commands, access diagnostics, and navigate the workspace.',
    category: 'Development', protocol: 'MCP',
    githubUrl: 'https://github.com/microsoft/vscode-mcp',
    npmPackage: '@microsoft/vscode-mcp',
    installCommand: 'npm install @microsoft/vscode-mcp',
    authorName: 'Microsoft', authorEmail: 'mcp@microsoft.com',
    status: 'approved', isVerified: true, isFeatured: false,
    viewCount: 4100, installCount: 2600, ratingAvg: '4.9', ratingCount: 234,
  },
  {
    name: 'Sentry MCP',
    slug: 'sentry-mcp',
    tagline: 'Query errors, issues, and performance data from Sentry',
    description: 'Sentry error tracking integration for AI agents. Query issues, read stack traces, analyze performance metrics, manage alerts, and triage production errors with natural language.',
    category: 'Development', protocol: 'MCP',
    githubUrl: 'https://github.com/getsentry/sentry-mcp',
    npmPackage: '@sentry/mcp-server',
    installCommand: 'npm install @sentry/mcp-server',
    authorName: 'Sentry', authorEmail: 'integrations@sentry.io',
    status: 'approved', isVerified: true, isFeatured: false,
    viewCount: 1800, installCount: 920, ratingAvg: '4.6', ratingCount: 84,
  },
  // CLOUD
  {
    name: 'AWS Lambda MCP',
    slug: 'aws-lambda-mcp',
    tagline: 'Invoke, deploy, and monitor AWS Lambda functions from AI agents',
    description: 'AWS Lambda integration for AI agents. Invoke functions, deploy new versions, manage environment variables, read CloudWatch logs, and monitor invocation metrics.',
    category: 'Cloud', protocol: 'MCP',
    githubUrl: 'https://github.com/aws/mcp',
    npmPackage: '@aws/mcp-server-lambda',
    installCommand: 'npm install @aws/mcp-server-lambda',
    authorName: 'Amazon Web Services', authorEmail: 'mcp@amazon.com',
    status: 'approved', isVerified: true, isFeatured: false,
    viewCount: 1600, installCount: 810, ratingAvg: '4.5', ratingCount: 71,
  },
  {
    name: 'Google Cloud MCP',
    slug: 'google-cloud-mcp',
    tagline: 'Manage GCP resources, BigQuery, and Cloud Storage from AI agents',
    description: 'Google Cloud Platform integration for AI agents. Query BigQuery datasets, manage Cloud Storage buckets, read Pub/Sub messages, and interact with Cloud Run services.',
    category: 'Cloud', protocol: 'MCP',
    githubUrl: 'https://github.com/googleapis/mcp-toolbox-for-databases',
    npmPackage: '@google-cloud/mcp-server',
    installCommand: 'npm install @google-cloud/mcp-server',
    authorName: 'Google', authorEmail: 'mcp@google.com',
    status: 'approved', isVerified: true, isFeatured: false,
    viewCount: 2200, installCount: 1100, ratingAvg: '4.7', ratingCount: 98,
  },
  {
    name: 'Cloudflare MCP',
    slug: 'cloudflare-mcp',
    tagline: 'Manage Workers, KV, R2, and D1 from AI agents',
    description: 'Cloudflare platform integration. Deploy and manage Workers, read and write KV namespaces, manage R2 buckets, query D1 databases, and configure DNS — all from your agent.',
    category: 'Cloud', protocol: 'MCP',
    githubUrl: 'https://github.com/cloudflare/mcp-server-cloudflare',
    npmPackage: '@cloudflare/mcp-server-cloudflare',
    installCommand: 'npm install @cloudflare/mcp-server-cloudflare',
    authorName: 'Cloudflare', authorEmail: 'devrel@cloudflare.com',
    status: 'approved', isVerified: true, isFeatured: false,
    viewCount: 2700, installCount: 1400, ratingAvg: '4.8', ratingCount: 127,
  },
  // COMMUNICATION
  {
    name: 'Gmail MCP',
    slug: 'gmail-mcp',
    tagline: 'Read, send, and manage Gmail from your AI agent',
    description: 'Gmail integration for AI agents. Read and send emails, manage labels, search messages, handle attachments, and draft responses. Supports OAuth and service accounts.',
    category: 'Communication', protocol: 'MCP',
    githubUrl: 'https://github.com/modelcontextprotocol/servers',
    npmPackage: '@modelcontextprotocol/server-gmail',
    installCommand: 'npm install @modelcontextprotocol/server-gmail',
    authorName: 'Anthropic', authorEmail: 'mcp@anthropic.com',
    status: 'approved', isVerified: true, isFeatured: false,
    viewCount: 3800, installCount: 2200, ratingAvg: '4.7', ratingCount: 198,
  },
  {
    name: 'Discord MCP',
    slug: 'discord-mcp',
    tagline: 'Send messages, manage servers, and read channels from AI agents',
    description: 'Discord integration for AI agents. Send and read messages, manage server channels, create webhooks, handle reactions, and moderate communities from your AI pipeline.',
    category: 'Communication', protocol: 'MCP',
    githubUrl: 'https://github.com/v-3/discordmcp',
    npmPackage: 'discord-mcp',
    installCommand: 'npm install discord-mcp',
    authorName: 'Community', authorEmail: 'discord-mcp@proton.me',
    status: 'approved', isVerified: false, isFeatured: false,
    viewCount: 2100, installCount: 1100, ratingAvg: '4.5', ratingCount: 92,
  },
  {
    name: 'Twilio MCP',
    slug: 'twilio-mcp',
    tagline: 'Send SMS, make calls, and manage Twilio from AI agents',
    description: 'Twilio communications platform for AI agents. Send SMS and WhatsApp messages, initiate voice calls, manage phone numbers, and query message logs from your agent.',
    category: 'Communication', protocol: 'MCP',
    githubUrl: 'https://github.com/twilio-labs/mcp',
    npmPackage: '@twilio-labs/mcp',
    installCommand: 'npm install @twilio-labs/mcp',
    authorName: 'Twilio', authorEmail: 'help@twilio.com',
    status: 'approved', isVerified: true, isFeatured: false,
    viewCount: 1500, installCount: 760, ratingAvg: '4.6', ratingCount: 67,
  },
  {
    name: 'Microsoft Teams MCP',
    slug: 'teams-mcp',
    tagline: 'Post messages, join meetings, and manage Teams from AI agents',
    description: 'Microsoft Teams integration for AI agents. Send messages to channels and chats, manage meetings, read team activity, and automate notifications in your organization.',
    category: 'Communication', protocol: 'MCP',
    githubUrl: 'https://github.com/microsoft/teams-mcp',
    npmPackage: '@microsoft/teams-mcp',
    installCommand: 'npm install @microsoft/teams-mcp',
    authorName: 'Microsoft', authorEmail: 'mcp@microsoft.com',
    status: 'approved', isVerified: true, isFeatured: false,
    viewCount: 1900, installCount: 990, ratingAvg: '4.6', ratingCount: 85,
  },
  // PRODUCTIVITY
  {
    name: 'Airtable MCP',
    slug: 'airtable-mcp',
    tagline: 'Read and write Airtable bases, tables, and records from AI agents',
    description: 'Airtable integration for AI agents. Query records with filters, create and update entries, manage attachments, and work with linked records and formulas.',
    category: 'Productivity', protocol: 'MCP',
    githubUrl: 'https://github.com/domdomegg/airtable-mcp-server',
    npmPackage: 'airtable-mcp-server',
    installCommand: 'npm install airtable-mcp-server',
    authorName: 'Community', authorEmail: 'adam@domdomegg.com',
    status: 'approved', isVerified: false, isFeatured: false,
    viewCount: 1300, installCount: 670, ratingAvg: '4.4', ratingCount: 56,
  },
  {
    name: 'Asana MCP',
    slug: 'asana-mcp',
    tagline: 'Create tasks, manage projects, and track work in Asana from AI agents',
    description: 'Asana project management integration for AI agents. Create and update tasks, manage projects and portfolios, assign work, set due dates, and track completion.',
    category: 'Productivity', protocol: 'MCP',
    githubUrl: 'https://github.com/Asana/asana-mcp',
    npmPackage: '@asana/mcp-server',
    installCommand: 'npm install @asana/mcp-server',
    authorName: 'Asana', authorEmail: 'api@asana.com',
    status: 'approved', isVerified: true, isFeatured: false,
    viewCount: 1200, installCount: 610, ratingAvg: '4.5', ratingCount: 53,
  },
  {
    name: 'Google Calendar MCP',
    slug: 'google-calendar-mcp',
    tagline: 'Create events, check availability, and manage calendars from AI agents',
    description: 'Google Calendar integration for AI agents. Create and update events, check free/busy times, manage recurring events, and send invites — perfect for scheduling automation.',
    category: 'Productivity', protocol: 'MCP',
    githubUrl: 'https://github.com/nspady/google-calendar-mcp',
    npmPackage: 'google-calendar-mcp',
    installCommand: 'npm install google-calendar-mcp',
    authorName: 'Community', authorEmail: 'nspady@gmail.com',
    status: 'approved', isVerified: false, isFeatured: false,
    viewCount: 2400, installCount: 1300, ratingAvg: '4.6', ratingCount: 112,
  },
  {
    name: 'Obsidian MCP',
    slug: 'obsidian-mcp',
    tagline: 'Read, write, and search your Obsidian vault from AI agents',
    description: 'Obsidian knowledge base integration for AI agents. Read and write notes, search vault contents, manage tags and links, and interact with your second brain programmatically.',
    category: 'Productivity', protocol: 'MCP',
    githubUrl: 'https://github.com/calclavia/mcp-obsidian',
    npmPackage: 'mcp-obsidian',
    installCommand: 'npm install mcp-obsidian',
    authorName: 'Community', authorEmail: 'henry@calclavia.com',
    status: 'approved', isVerified: false, isFeatured: false,
    viewCount: 1700, installCount: 890, ratingAvg: '4.7', ratingCount: 78,
  },
  // AI & ML
  {
    name: 'OpenAI Assistants MCP',
    slug: 'openai-assistants-mcp',
    tagline: 'Create and manage OpenAI Assistants and threads from AI agents',
    description: 'OpenAI Assistants API integration. Create assistants with custom instructions, manage conversation threads, run completions, and handle tool calls — all from your MCP-compatible agent.',
    category: 'AI & ML', protocol: 'MCP',
    githubUrl: 'https://github.com/zekageri/openai-mcp-server',
    npmPackage: 'openai-mcp-server',
    installCommand: 'npm install openai-mcp-server',
    authorName: 'Community', authorEmail: 'zekageri@gmail.com',
    status: 'approved', isVerified: false, isFeatured: false,
    viewCount: 2800, installCount: 1500, ratingAvg: '4.5', ratingCount: 131,
  },
  {
    name: 'Hugging Face MCP',
    slug: 'huggingface-mcp',
    tagline: 'Run inference on Hugging Face models from AI agents',
    description: 'Hugging Face inference integration. Run text generation, image classification, embeddings, and custom model inference. Browse the model hub and deploy to Inference Endpoints.',
    category: 'AI & ML', protocol: 'MCP',
    githubUrl: 'https://github.com/evalstate/mcp-hfspace',
    npmPackage: 'mcp-hfspace',
    installCommand: 'npm install mcp-hfspace',
    authorName: 'Community', authorEmail: 'evalstate@proton.me',
    status: 'approved', isVerified: false, isFeatured: false,
    viewCount: 1900, installCount: 980, ratingAvg: '4.5', ratingCount: 86,
  },
  {
    name: 'Perplexity MCP',
    slug: 'perplexity-mcp',
    tagline: 'Real-time AI search and research for AI agents via Perplexity',
    description: 'Perplexity AI search integration. Perform deep research queries, get cited answers, and access real-time web information from within your AI agent pipelines.',
    category: 'AI & ML', protocol: 'MCP',
    githubUrl: 'https://github.com/tanker327/perplexity-ask-mcp',
    npmPackage: 'perplexity-ask-mcp',
    installCommand: 'npm install perplexity-ask-mcp',
    authorName: 'Community', authorEmail: 'tanker327@gmail.com',
    status: 'approved', isVerified: false, isFeatured: false,
    viewCount: 1400, installCount: 710, ratingAvg: '4.4', ratingCount: 61,
  },
  {
    name: 'Pinecone MCP',
    slug: 'pinecone-mcp',
    tagline: 'Query and manage vector embeddings in Pinecone from AI agents',
    description: 'Pinecone vector database integration for AI agents. Upsert and query vectors, manage indexes and namespaces, run similarity search, and power RAG pipelines.',
    category: 'AI & ML', protocol: 'MCP',
    githubUrl: 'https://github.com/pinecone-io/pinecone-mcp',
    npmPackage: '@pinecone-database/mcp',
    installCommand: 'npm install @pinecone-database/mcp',
    authorName: 'Pinecone', authorEmail: 'support@pinecone.io',
    status: 'approved', isVerified: true, isFeatured: false,
    viewCount: 2100, installCount: 1100, ratingAvg: '4.7', ratingCount: 94,
  },
  // FINANCE
  {
    name: 'QuickBooks MCP',
    slug: 'quickbooks-mcp',
    tagline: 'Query invoices, expenses, and reports from QuickBooks via AI agents',
    description: 'QuickBooks Online integration for AI agents. Query customers, invoices, expenses, and profit & loss reports. Create transactions, run reconciliations, and automate bookkeeping.',
    category: 'Finance', protocol: 'MCP',
    githubUrl: 'https://github.com/SaseQ/quickbooks-mcp-server',
    npmPackage: 'quickbooks-mcp-server',
    installCommand: 'npm install quickbooks-mcp-server',
    authorName: 'Community', authorEmail: 'saseq@proton.me',
    status: 'approved', isVerified: false, isFeatured: false,
    viewCount: 890, installCount: 440, ratingAvg: '4.3', ratingCount: 38,
  },
  {
    name: 'CoinGecko MCP',
    slug: 'coingecko-mcp',
    tagline: 'Real-time crypto prices, market data, and coin info for AI agents',
    description: 'CoinGecko crypto market data integration. Get real-time prices, market caps, trading volumes, historical data, and trending coins. Perfect for trading bots and DeFi agents.',
    category: 'Finance', protocol: 'MCP',
    githubUrl: 'https://github.com/pwh-pwh/coin-mcp-server',
    npmPackage: 'coin-mcp-server',
    installCommand: 'npm install coin-mcp-server',
    authorName: 'Community', authorEmail: 'pwh@proton.me',
    status: 'approved', isVerified: false, isFeatured: false,
    viewCount: 1100, installCount: 560, ratingAvg: '4.4', ratingCount: 49,
  },
  {
    name: 'Plaid MCP',
    slug: 'plaid-mcp',
    tagline: 'Connect bank accounts and query transactions from AI agents',
    description: 'Plaid financial data integration for AI agents. Link bank accounts, query transactions and balances, categorize spending, and build personal finance agents.',
    category: 'Finance', protocol: 'MCP',
    githubUrl: 'https://github.com/plaid/plaid-mcp',
    npmPackage: '@plaid/mcp-server',
    installCommand: 'npm install @plaid/mcp-server',
    authorName: 'Plaid', authorEmail: 'developers@plaid.com',
    status: 'approved', isVerified: true, isFeatured: false,
    viewCount: 1300, installCount: 660, ratingAvg: '4.6', ratingCount: 57,
  },
  // ANALYTICS
  {
    name: 'Mixpanel MCP',
    slug: 'mixpanel-mcp',
    tagline: 'Query Mixpanel events, funnels, and user analytics from AI agents',
    description: 'Mixpanel product analytics integration. Query event data, build funnels, analyze retention, segment users, and generate insights using natural language.',
    category: 'Analytics', protocol: 'MCP',
    githubUrl: 'https://github.com/dragonkhoi/mixpanel-mcp',
    npmPackage: 'mixpanel-mcp',
    installCommand: 'npm install mixpanel-mcp',
    authorName: 'Community', authorEmail: 'dragonkhoi@gmail.com',
    status: 'approved', isVerified: false, isFeatured: false,
    viewCount: 820, installCount: 410, ratingAvg: '4.3', ratingCount: 35,
  },
  {
    name: 'Google Analytics MCP',
    slug: 'google-analytics-mcp',
    tagline: 'Query GA4 traffic, conversions, and audiences from AI agents',
    description: 'Google Analytics 4 integration for AI agents. Query sessions, events, conversions, and user properties. Build reports, compare date ranges, and analyze campaign performance.',
    category: 'Analytics', protocol: 'MCP',
    githubUrl: 'https://github.com/Infuzu/infuzu-mcp-google-analytics',
    npmPackage: 'infuzu-mcp-google-analytics',
    installCommand: 'npm install infuzu-mcp-google-analytics',
    authorName: 'Infuzu', authorEmail: 'devs@infuzu.com',
    status: 'approved', isVerified: false, isFeatured: false,
    viewCount: 1400, installCount: 720, ratingAvg: '4.4', ratingCount: 62,
  },
  {
    name: 'Segment MCP',
    slug: 'segment-mcp',
    tagline: 'Query Segment events, traits, and audiences from AI agents',
    description: 'Segment customer data platform integration. Query user traits and events, build audiences, inspect source data, and route data to downstream destinations.',
    category: 'Analytics', protocol: 'MCP',
    githubUrl: 'https://github.com/segmentio/segment-mcp',
    npmPackage: '@segment/mcp-server',
    installCommand: 'npm install @segment/mcp-server',
    authorName: 'Segment', authorEmail: 'friends@segment.com',
    status: 'approved', isVerified: true, isFeatured: false,
    viewCount: 940, installCount: 470, ratingAvg: '4.5', ratingCount: 41,
  },
  {
    name: 'PostHog MCP',
    slug: 'posthog-mcp',
    tagline: 'Open-source product analytics and session replay for AI agents',
    description: 'PostHog product analytics integration for AI agents. Query events, feature flags, experiments, session recordings, and funnels. Works with cloud and self-hosted instances.',
    category: 'Analytics', protocol: 'MCP',
    githubUrl: 'https://github.com/PostHog/posthog-mcp',
    npmPackage: '@posthog/mcp-server',
    installCommand: 'npm install @posthog/mcp-server',
    authorName: 'PostHog', authorEmail: 'hey@posthog.com',
    status: 'approved', isVerified: true, isFeatured: false,
    viewCount: 1100, installCount: 560, ratingAvg: '4.6', ratingCount: 48,
  },
  {
    name: 'Datadog MCP',
    slug: 'datadog-mcp',
    tagline: 'Query metrics, logs, and APM traces from Datadog via AI agents',
    description: 'Datadog observability integration for AI agents. Query infrastructure metrics, search logs, inspect distributed traces, manage monitors and alerts, and analyze SLO compliance.',
    category: 'Analytics', protocol: 'MCP',
    githubUrl: 'https://github.com/DataDog/datadog-mcp-server',
    npmPackage: '@datadog/mcp-server',
    installCommand: 'npm install @datadog/mcp-server',
    authorName: 'Datadog', authorEmail: 'dev@datadoghq.com',
    status: 'approved', isVerified: true, isFeatured: false,
    viewCount: 1800, installCount: 920, ratingAvg: '4.7', ratingCount: 82,
  },
];

async function seedMore() {
  console.log('🌱 Adding 35 more servers to ForgeLink...');
  try {
    const inserted = await db.insert(mcpServers).values(newServers as any).returning();
    console.log(`✅ Inserted ${inserted.length} new servers`);
    const all = await db.select().from(mcpServers);
    console.log(`📊 Total servers: ${all.length}`);
  } catch (error) {
    console.error('❌ Seed failed:', error);
    throw error;
  } finally {
    await client.end();
  }
}

seedMore();
